### ISSUE TITLE
Missing step in Documentation

### ISSUE THREAD

**Issue by tokjun** [openigtlink/ROS-IGTL-Bridge#1]
When creating a ROS workspace, cmake needs to be called:

```
$ mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws/src
$ catkin_init_workspace
$ cmake .                             <-- here
$ source devel/setup.bash
```

**Comment by Tob19** [comment]
Hi Junichi,
 
sorry for the late reply. Your mails were in my spam folder and I had not checked it for a while.
 
The cmake command is called when executing the catkin_init_workspace command. The command order is from the standard ROS tutorial for setting up a workspace:
http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment
 
Regarding the missing header:
The header files should be created automatically in the Build-Process.
Which ROS version/operating system do you use?
 
Best,
 
Tobias
 
-----Ursprüngliche Nachricht-----
 Von: "Junichi Tokuda" [notifications@github.com]
 Gesendet: Fr. 14.10.2016 16:34
 An: "openigtlink/ROS-IGTL-Bridge" [ROS-IGTL-Bridge@noreply.github.com]
 Betreff: [openigtlink/ROS-IGTL-Bridge] Missing step in Documentation (#1)

When creating a ROS workspace, cmake needs to be called:
$ mkdir -p ~/catkin_ws/src$ cd ~/catkin_ws/src$ catkin_init_workspace$ cmake .                             <-- here$ source devel/setup.bash—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----

---

Die Bundesliga hat begonnen! Alle Tore, alle Ergebnisse, alle News: Pocket Liga jetzt im AppStore oder Google Play Store herunterladen - kostenlos!
